### ISSUE TITLE
U.K. COVID data

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#1]
Great to find this. Exquisite work!

Everybody is talking about China but I am still amazed how difficult is to find detailed info for the US and UK.

Because I did not find UK on the list I will add here what I know about it:
https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales
See the April 3 update. In the Excel file you will find death counts by age but not confirmed cases.

Regards,
Marius

**Comment by mpascariu** [comment]
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/878916/Weekly_all_cause_mortality_surveillance_week_15_2020_report.pdf

**Comment by timriffe** [comment]
Thank you, UK, England and Wales, Northern Ireland, and Scotland are all in
the works! Keep the tips coming in!
