### ISSUE TITLE
High number of deaths for ages 0-5 in the United Kingdom

### ISSUE THREAD

**Issue by GBarnsley** [timriffe/covid_age#116]
The data (in Output_5) shows a very high number of deaths from covid for ages 0-5 in the UK data set, higher than any other age group. This isn't present, as far as I can see, in the England, England and Wales, Scotland, and Northern Ireland data. A jump in deaths seems to occur at the start of 2021, so this might be to do with swapping to the 2021 ONS dataset?

**Comment by timriffe** [comment]
Thanks @GBarnsley we will investigate this rupture, much appreciated. I've forwarded the question to the curator of our UK series, and will reach out to others if needed. Best wishes

**Comment by fcorowe** [comment]
Hi @GBarnsley, Sorry that it has taken me this long to inspect this issue and get back to you. You are correct. It seems that there is a slight variation as to how the ONS reports the 2021 data and that change had not been reflected in the code used to process the data. I have updated the code and checked the data. It looks all good to me. I will close the issue for now, but feel free to open a new one if you notice similar issues.

**Comment by fcorowe** [comment]
@timriffe can you close this issue please.

**Comment by timriffe** [comment]
Thanks @fcorowe !
@GBarnsley this update will make its way into the output files in 1-2 days I expect.
