### ISSUE TITLE
UK death data

### ISSUE THREAD

**Issue by Chaserrya** [timriffe/covid_age#118]
Hello @timriffe,
I've noticed that there's some abnormal data in death data of United Kingdom. As a cumulative death data, using age 80 data as example, it's 34500.8 on 2021.01.01 but 9721.2 on 2021.01.08. I'm wondering how's that happended. I've compared with the data sourse of UK you provided, and it seems fine in the data source. Could you provide any possible explaination of that. Thank you so much!

**Comment by fcorowe** [comment]
Hi @Chaserrya, Sorry that it took me this long to get back to you, and thanks for flagging this issue. It seems that at some point the ONS reported the data slightly different and the code used to process the data has not reflect that change. I have updated the code and checked the data. It looks all good to me. I will close the issue for now, but feel free to open a new one if you notice similar issues.

**Comment by fcorowe** [comment]
@timriffe just realised I can't close the issue as I am not a collaborator on the repo.

**Comment by timriffe** [comment]
@Chaserrya this update should make it to the output files in 1-2 days I expect. Thanks @fcorowe !

**Comment by Chaserrya** [comment]
That's great! Thank you!
