### ISSUE TITLE
error when downloading data

### ISSUE THREAD

**Issue by liuyanguu** [timriffe/covid_age#142]
Sorry it's me again.
```
library(covidAgeData)
df <- download_covid(data = "Output_5")
```
gets
Error: The requested file (7tnfh) could not be found in node `mpwjq`
Same for "Output_10"
Any quick suggestions?

**Comment by eshom** [comment]
@liuyanguu Sorry for not responding quicker!

I've only came to know about this when an issue opened in my repo eshom/covid-age-data#5

I fixed the problem by changing to the long id format OSF uses, so this can be closed.

**Comment by liuyanguu** [comment]
No problem! Many thanks for solving the issue. I just download the data from OSF as an alternative so not a problem. But good it's fixed now.
