### ISSUE TITLE
Output consistency checks required!

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#20]
The harmonization process should maintain the consistency between sexes and both sex.

Below I am looking at the data in `Output_10.csv` and I can see that the sum of the values for `m` and `f` populations are far away from the count data in `b` by a large margin. Somewhere along the way from `InputDB` to `Output` must be a much bigger bug hidden in the lines. 

```r

> path <- "https://raw.githubusercontent.com/timriffe/covid_age/master/Data/Output_10.csv"
> cfr10 <- read.csv(
+   file = path,
+   header = TRUE,
+   skip = 1
+   )
> 
> cfr10 %>% 
+   filter(Country == "Spain",
+          Date == "02.05.2020") %>% 
+   select(-Cases, -Tests) %>% 
+   pivot_wider(names_from = Sex, values_from = Deaths) %>% 
+   mutate(`m+f` = m + f)
# A tibble: 22 x 10
   Country Region Code         Date         Age AgeInt       b     f     m `m+f`
   <fct>   <fct>  <fct>        <fct>      <int>  <int>   <dbl> <dbl> <dbl> <dbl>
 1 Spain   All    ES02.05.2020 02.05.2020     0     10     2.9    1     1      2
 2 Spain   All    ES02.05.2020 02.05.2020    10     10     7.4    3     2      5
 3 Spain   All    ES02.05.2020 02.05.2020    20     10    32.4    8    14     22
 4 Spain   All    ES02.05.2020 02.05.2020    30     10    84     22    35     57
 5 Spain   All    ES02.05.2020 02.05.2020    40     10   268.    69   113    182
 6 Spain   All    ES02.05.2020 02.05.2020    50     10   831.   160   404    564
 7 Spain   All    ES02.05.2020 02.05.2020    60     10  2233.   438  1077   1515
 8 Spain   All    ES02.05.2020 02.05.2020    70     10  6263.  1349  2900   4249
 9 Spain   All    ES02.05.2020 02.05.2020    80     10 10423.  3084  3987   7071
10 Spain   All    ES02.05.2020 02.05.2020    90     10  4266.  1654. 1206.  2860
# ... with 12 more rows

```

**Comment by timriffe** [comment]
a teeny tiny bug. `rescale_sexes()` wasn't being triggered properly by `do_we_rescale_sexes()`. Now fixed, re-running processes. You're right, this is a consistency check to run after a processing run.

This constraint happens before PCLM, but I guess it could be lost if age groups are split. Presently, after PCLM there is no re-constraining of this kind. Should we add it?

**Comment by mpascariu** [comment]
Excellent! It looks much better.
In the example from above there still are some minor differences especially in the `90` and `100`  age classes. 

```r
   Country Region Code         Date         Age AgeInt       b      f      m   `m+f`
   <fct>   <fct>  <fct>        <fct>      <int>  <int>   <dbl>  <dbl>  <dbl>   <dbl>
10 Spain   All    ES02.05.2020 02.05.2020    90     10  4266.  2486.  1807.   4293. 
11 Spain   All    ES02.05.2020 02.05.2020   100      5   852.   594.   231.    825. 
```

So far we have written tests for the input data. I think it will not hurt if we can run them over the final output as well.

I can take care of this in a separate script.

**Comment by timriffe** [comment]
Great, I'll close this issue. FYI, `f` and `m` are forced to sum to `b` now after splitting. Previously they were not. So, moving forward I don't expect this flag to be thrown.
