### ISSUE TITLE
Denmark strange patterns

### ISSUE THREAD

**Issue by vzarulli** [timriffe/covid_age#21]
Deaths: As the deaths reported in the output are the cumulative ones over time, they cannot be decreasing. The total number of deaths increases day by day, as expected. But if I break them down by age, some age groups are decreasing in some days. Please see below.
![DK_deaths_17052020](https://user-images.githubusercontent.com/65513286/82161375-772d5080-989c-11ea-84dd-c833bd53f476.png)

Sex ratio of the Cases: there is a strange convergence of many ages towards a value of 1 on one single day. Please see below.
![DK_sr_cases2_17052020](https://user-images.githubusercontent.com/65513286/82161452-0dfa0d00-989d-11ea-938b-ce618ddb385f.png)

**Comment by timriffe** [comment]
The convergence looks to have been a data entry error, amended some time ago, sorry for the late response to that one:
```
osf_retrieve_file("5hyvs") %>%
  osf_download(conflicts = "overwrite") 

# This reads it in
Output_5 <-  read_csv("Output_5.csv",
                       skip = 3,
                       col_types = "ccccciiddd")
# convert to date class
Output_5 <- 
  Output_5 %>% 
  mutate(Date = dmy(Date))

Output_5 %>% 
  filter(Country == "Denmark") %>% 
  select(-Deaths,-Tests) %>% 
  pivot_wider(names_from = "Sex", values_from = "Cases") %>% 
  mutate(SR = m/f,
         Date = ymd(Date)) %>% 
  ggplot(aes(x=Date,y=SR,group=Age,color=as.factor(Age)))+
  geom_line()+
  scale_y_log10()
```
![image](https://user-images.githubusercontent.com/904603/87871148-5b365000-c9ae-11ea-911d-fd87047f4020.png)
