### ISSUE TITLE
Your dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by k-goncharova** [timriffe/covid_age#25]
Hello,

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/JWULOO.

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by timriffe** [comment]
Thanks for reaching out, we could maintain the entry, yes. Some guidance would be helpful to get started. Please send an email re that.

**Comment by muntasir-masum** [comment]
I would be happy to help. Yes, I am looking forward to the instructions and guidelines as well.

**Comment by k-goncharova** [comment]
Hello,

Thank you for your response and willingness to contribute. Please register
in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you
the necessary permissions for editing your dataset. Then it would be also
helpful, if you could add metadata (description, keywords) to your dataset
in Dataverse.

Kira Goncharova

**Comment by muntasir-masum** [comment]
Thank you. I have signed up. I will work on the dataset.

**Comment by k-goncharova** [comment]
Thank you! I've just given you the permissions for editing the dataset. Feel free to contact me, if you might need any help with the update.
