### ISSUE TITLE
Texas total cases by age is off from total cases by ~10x

### ISSUE THREAD

**Issue by bradknox** [timriffe/covid_age#33]
As of August 13, the total case count for Texas _when added up by age groups_ in this dataset is 43,409. The "TOT" line for all ages is 513,575, which is in line with numbers I see elsewhere. 

I'm guessing that Texas simply didn't report ages for more than 90% of cases, even though it is reporting them for all or nearly all of deaths. Does the discrepancy above come from the state's reporting or is it an actual error?

If the former, should there be some way that such data limitations are reported within the data set?

Lastly, thanks for making all of this data available! It's a wonderful resource to have in one place.

**Comment by timriffe** [comment]
Thanks @bradknox, this is the right place to report such problems. In this case we're aware of it. On July 23 I sent the following email to Texas DSHS:

> Dear Texas DSHS,
> 
> Thanks for your great open data! I've been using the file "Cases over Time by County" from your additional data page 
> https://dshs.texas.gov/coronavirus/TexasCOVID19DailyCountyCaseCountData.xlsx
> Specifically, the tabs "Cases by age group" and "Fatalities by age group". This data is a primary source for the Texas series in COVerAGE-DB, an open access database of demographically structured COVID-19 data (https://osf.io/mpwjq/). 
> 
> Issue
> The data in those tabs represent under 10% of the cases and deaths registered in Texas. If the discrepancy were smaller, we would simply rescale the age distribution to match the recorded total. For the Texas data this seems risky, since the age-specific data is such a small fraction of the total. 
> 
> Solution
> The total cases for each demographic breakdown is the same right now (29588)- same for age, gender, ethnicity. I therefore suspect that these tabulations were based on cases where ALL variables (age, sex, ethnicity) were not missing. If instead these demographic tabs were tabulated independently of one another, my guess is at least 80% of cases will have a known age, and >90% will have a known gender. If this is roughly correct, it might make sense to implement this simple change in the way this daily spreadsheet is produced. Does this make sense?
> 
> Request
> Is there a procedure in place to request a specific data extract (or add it to your repertoire of additional data files for public download)? Specifically, I would like to request a (retrospective) daily time series of cumulative (or new) cases and deaths by age (5- year age groups) AND sex. However, not filtered down to cases (deaths) where both variables are known, but including counts of known age and unknown sex (and vice versa). This tabulation doesn't need to have sub-geographies, just statewide data, so I don't see a risk of data privacy issues. The data would be of public value for demographers and epidemiologists, and it'd be an important part of the COVerAGE-DB global database. To be explicit, the data structure I'm requesting would look something like this (example data)
> 
> Date     | Sex    | Age | Cases (cumulative) | Deaths (cumulative)
> 5-1-2020 | Female | 0   | 100                | 1
> ...
> 
> A benefit to producing this entire file daily would be that the series would reflect whatever retrospective corrections happen to your case report microdata (late registrations, duplicate removal, etc etc).
> 
> Thank you for your attention and consideration, and thank you for your important work,
> 
> Healthy wishes,

They did not respond, but I still think that this is what's going on. I don't really have a solution either. This is an extreme such case in this database. Any ideas how to best flag such data for users?

**Comment by timriffe** [comment]
We will include such information in a metadata field for general observations I think, anyway, let's hope they come through will a full time series so we can swap out the whole series, you never know.
