### ISSUE TITLE
US Ohio data

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#39]
I can see that in `Output_10.csv` we have recorded cases as early as January 2, 2020. Supposedly, the virus was present in China only at that time. 

Or a 2D smoothing is used at this stage to reconstruct the early records?

**Comment by timriffe** [comment]
It's not 2D smoothing (yet!).

Here's a glimpse at those early onset cases from the Ohio source data:

```
County Sex   `Age Range` `Onset Date` `Date Of Death` `Admission Date`
  <chr>  <chr> <chr>       <chr>        <chr>           <chr>           
1 Erie   Fema… 80+         1/2/2020     NA              NA              
2 Licki… Male  40-49       1/2/2020     NA              NA              
3 Mahon… Fema… 80+         1/2/2020     NA              NA              
4 Warren Fema… 40-49       1/2/2020     NA              NA              
```

I'm not sure how stable these first cases are though. The Ohio series is tabulated from this finer grained data. An option would be to start the series after a certain number of cases (say 20?) have been accumulated.

This also happens in some other COVerAGE-DB series, such as Ontario.

**Comment by mpascariu** [comment]
I see. I was not aware of this. However, if the original source reports them... could be true. 
By any chance, these are not the cases transferred from the Diamond Princess cruise ship in mid January?

**Comment by timriffe** [comment]
it's plausible: https://www.newsbreak.com/ohio/cleveland/news/1507242927701/northeast-ohio-couple-stays-positive-aboard-quarantined-cruise-ship
