### ISSUE TITLE
Danish females

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#4]
Clearly this is a project that I want in. So I am continuing to post my observations.

I couldn't find the source for the Danish data or the original data in `inputDB.csv`. Can we have a database with sources? Also would be nice to indicate in the output the degree to which the data has been modeled and the perceived data quality (good, bad, mediocre...).

Now, looking at the cfr in the Danish female population as of April 9 we can see an unusual pattern.

![Rplot2](https://user-images.githubusercontent.com/6264977/79555279-9b302300-809f-11ea-90eb-b4b6c80a033a.png)

Can we explain this?

**Comment by timriffe** [comment]
Denmark is temporarily removed as there were some errors in data entry that
will be fixed. Will send source later. Comprehensive sources list is in
construction at the moment. Will get back to you soon. I also have noticed
a hump like that in old ages in other populations FWIF, not sure yet

**Comment by mpascariu** [comment]
I am attaching here some data that I collected from public places. You have most of it except maybe some early Korean records.
[CFR-Trends_by_Age_20200415.xlsx](https://github.com/timriffe/covid_age/files/4492157/CFR-Trends_by_Age_20200415.xlsx)

**Comment by mpascariu** [comment]
The most recent Spanish female data also looks a bit funny at older ages.
