### ISSUE TITLE
US Virginia Data

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#40]
In `Output_10.csv` the number of confirmed cases and deaths in Virginia appear exceptionally high.  We can see more than 7 mil cases.

According to the US Census data the entire state has a mid-2019 population of 4,248,373.

```r
> path <- "Output_10_20200828.csv"
> data <- read.csv(
+   file = path,
+   header = TRUE,
+   skip = 3
+ ) %>% 
+   filter(Region == "Virginia",
+          Date == "27.08.2020") %>% 
+   group_by(Region) %>% 
+   summarise_if(is.numeric, sum )
>   
> 
> data
# A tibble: 1 x 6
  Region     Age AgeInt    Cases  Deaths Tests
  <fct>    <int>  <int>    <dbl>   <dbl> <dbl>
1 Virginia   550    105 7922068. 208726.    NA
```

**Comment by mpascariu** [comment]
Maybe the data at the `totals` level could be periodically crosschecked against the JHU record (allowing for a reasonable deviance of course).

**Comment by timriffe** [comment]
seems to be a likely column id error. I'll look into this and fix. And yes,
good call on the external validity checks.

**Comment by timriffe** [comment]
Got it, it seems the source data may have switched from *new* cases and deaths to *cumulative* cases and deaths some time recently. With an automatic external check in place this would have been picked up automatically. Corrected data should appear in the output within 24 hours. I will close this issue after verifying that this is so.

Thank you for reporting as usual!
