### ISSUE TITLE
Data availability for France

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#41]
Hi Tim,
Could you please let me know the reason why the availability of French data stops in July? Can we help you somehow to bring it up to date? Thanks a lot.

**Comment by timriffe** [comment]
From the collector:

> The source don’t explain why, but data indeed stops in July. That should be fix today, a message on the database say “Daily data from July 27 to August 30 should be updated on Monday 31/08/2020”.

So I guess sit tight.

**Comment by mpascariu** [comment]
Great! Thanks.

**Comment by mpascariu** [comment]
We can see that the death records is up to date, however the `cases` statistic is stuck in July. Is there a reason for this?

**Comment by timriffe** [comment]
When the collector updated there was no new data for cases available at that time. Now that person is training others to take over the work, and I understand they are evaluating an alternative source.

**Comment by timriffe** [comment]
Cases and Tests are updated into January 6 and Deaths through Feb 4th at this time, so I'm closing the issue for now. There are some aspects of the French series that I think are worthy of further consideration, but the collectors are already aware of these things, so it's not part of this issue
