### ISSUE TITLE
Data availability for Germany

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#48]
Dear COVerAGE team,
I've noticed that the data inputs and outputs for Germany have stopped in August. Could we please have an update on this?

Suggestion: 

I think it would be a good idea to have a database news section somewhere where important updates and developments are shared (maybe in 1 sentence).  Also we could produce a "data-availability table" where for each region to have specified the start and the end of the data, perceived quality and info about missing data. I would be of a great help to all of us who are working with your amazing data frequently.

Regards,
Marius

**Comment by timriffe** [comment]
yikes, sorry it took so long, there was a glitch with the automatic updates that made it look they were happening to us but then they weren't making it through the chain. Germany (and the Länder) are now updated, and should be updated daily now. We will figure out a system so we can catch these things earlier. If you ever get a moment, would be nice to chat for your perspective on our processing robustness, and also on a forthcoming data quality file.
Thanks Marius,
Tim

**Comment by mpascariu** [comment]
Thanks Tim. Yes, let's organize a call soon, it would be great to be updated on what is happening behind the stage and see how can I help next.
