### ISSUE TITLE
Data Duplication in US Subset

### ISSUE THREAD

**Issue by mwiry** [timriffe/covid_age#50]
Hi all,

Today, when working with the US subset of the data, I noticed some duplication but with differing values. Specifically, for any given Region, Sex, and Age I was expecting there to be a single observation; however, this is not the case. For example, Arizona on 9/26/20 for Sex equal to b and Age equal to 0 has two observations with differing case, test, and death values - the lines from the CSV file are included below for clarity. Can you provide some clarification here? As of this writing, I identified 1407 such instances in the US data.

USA, Arizona, US_AZ 26.09.2020, 26.09.2020, b, 0, 5, 3531.4, 0.4, 24559.3

USA, Arizona, US_CDC_AZ26.09.2020, 26.09.2020, b, 0, 5, NA, 1, NA

Thanks!

**Comment by timriffe** [comment]
Hi @mwiry 
Thanks for your message. In this case we collect from two sources, but you can only detect it in the `Code` variable, in a strange way, sorry about this. `"US_AZ_*"` comes from a state source, whereas `"US_CDC_AZ"` comes from the CDC (just deaths). Sometime soon we'll drop the date component of the `Code` variable.
