### ISSUE TITLE
A question on presenting data by time --- is the database built cumulatively?

### ISSUE THREAD

**Issue by liuyanguu** [timriffe/covid_age#73]
Thanks again for the great work. I wish to double-check a question:
If I want to show how is the situation in, for example, last October, could I just filter the latest dataset by `Date`? 
I assume the database is built cumulatively: so whenever there is an update in a country, the new data is appended to the old one. Is this roughly the case? 
Many thanks!

**Comment by timriffe** [comment]
yes, series are cumulative at this time. We do aim to offer decumulated series in the future, but this will require implementing more kinds of harmonization that we haven't got to yet. Anyway, yes, just pick out the date you need and you can consider it a snapshot. If things aren't as you expect, please report. Thank you!

**Comment by liuyanguu** [comment]
Thank you for your quick reply!
