### ISSUE TITLE
US Cook County mind-blowing data

### ISSUE THREAD

**Issue by mpascariu** [timriffe/covid_age#8]
... and not properly anonymized i'd say, can be found [here](https://datacatalog.cookcountyil.gov/Public-Safety/Medical-Examiner-Case-Archive-COVID-19-Related-Dea/3trz-enys).

I don't know if you are aware of this, but you can find seriatim death data (including COVID related). This might be a sign that more high quality data is coming from the US.

However, if you know somebody close to the source it would be nice to raise a warning and send them an email explaining that we will gladly use the data as is but this can generate a reputational risk on their side.

**Comment by timriffe** [comment]
You are right, that's for sure revealing too much. I think we will aim to add Chicago, thanks for pointing this out
