### ISSUE TITLE
USA all-region cases seems to be 0 in the output dataset?

### ISSUE THREAD

**Issue by liuyanguu** [timriffe/covid_age#82]
I just refreshed the data, and it seems the cases for USA become 0? 

```
library(covidAgeData)
library(data.table)
dt5_ori <- download_covid(data = "Output_5", temp = TRUE,
                            verbose = FALSE, progress = FALSE, return = "data.table")
dt5_ori[Country=="USA" & Region == "All" & !is.na(Cases), table(Cases)]
```
Cases
   0 
3633

The numbers exist last week in the earlier versions of the database.

**Comment by timriffe** [comment]
Thank you for reporting @liuyanguu we will investigate this Thursday and resolve ASAP

**Comment by timriffe** [comment]
ASAP turned out to be longer than expected, there was a deeper issue at core in keeping our processing pipeline up with the size of the database. Production code should be sorted out now, and has begun a new run, which will ideally end up on osf in less than 10 hours. Crossing fingers.

**Comment by timriffe** [comment]
This seems to be fixed now, so I'm closing this issue, thanks again for your early report!

**Comment by liuyanguu** [comment]
Great! Many thanks for your quick response!!
