### ISSUE TITLE
France all-region cases seem to lost (mostly)

### ISSUE THREAD

**Issue by liuyanguu** [timriffe/covid_age#97]
```
library(covidAgeData)
library(data.table)
dt5_ori <- download_covid(data = "Output_5", temp = TRUE,
                          verbose = FALSE, progress = FALSE, return = "data.table")
dt5_ori[Country=="France" & Region == "All" & Date=="21.02.2021" & Sex=="b" , sum(Cases, na.rm = TRUE)]
```
gives 5700.1.
On last Monday (3/1) the number was 2.8 million
(`Date == "21.02.2021"` is the latest date with data available)

This is comparing the "Output_5" datasets I downloaded on 3/8 (column `COVerAGE-DB`) to the 3/1 one (column `COVerAGE-DB_old`), but this issue emerged since the 3/3 dataset. 
<img src="https://user-images.githubusercontent.com/11966330/110366987-16caf380-8015-11eb-8256-d66ffd2dfa51.png" height="100">
As we can see, Spain and Portugal also have some decrease in numbers.

I am finalizing a dashboard that updates weekly using COVerAGE-DB, so I guess I will check these general consistency things for you every week.

**Comment by timriffe** [comment]
Many many thanks for reporting. I'm investigating France first. It was updated today, and I don't see the problem immediately in the input data. Cases and Tests only come up to 1 Feb, 2021. Total Cases will be 3104045 on that date when it is done processing tomorrow. I've asked the maintainer whether there's anything to add. I suspect that these discrepancies may occur when our ECDC collection gets ahead of the country-specific ones. I've just switched some code to make sure ECDC never overrides certain of our country series, even if they get behind. Spain for instance is derived from a single harmonized source, which is retrospectively corrected, so I think a correction of that magnitude is allowable, but it invites one to check whether it implies a series interruption. The Portugal one is almost certainly an ECDC anomaly (potentially a parsing error), and it will be removed for tomorrow's update. Then the most recent update will be 16 Feb, 2021. Please please continue reporting such anomalies!

**Comment by liuyanguu** [comment]
Many thanks Tim! Now the cases are fixed but the deaths are wrong for France and Portugal (Date `05.03.2021`)
```
library(covidAgeData)
library(data.table)
dt5_ori <- download_covid(data = "Output_5", temp = TRUE,
                          verbose = FALSE, progress = FALSE, return = "data.table")
dt5_ori[Country=="France" & Region == "All" & Date=="05.03.2021" & Sex=="b" , sum(Deaths, na.rm = TRUE)]
```
gives 67422341

**Comment by timriffe** [comment]
Thanks again, found the problem with France, and it will be fixed in the next update. Apologies for the delay!

**Comment by liuyanguu** [comment]
There is no hurry, but just curious when will the next update be? I just run the same code above and got the same (incorrect) results.

**Comment by timriffe** [comment]
Hi apologies for this, it's been fixed at the source, but hasn't yet escalated through the processing chain. We're behind on processing due to changes in production, but hope to be back to daily updates in the next day or two. Sorry for this annoyance.

**Comment by liuyanguu** [comment]
The issue is fixed. Many thanks!
